//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2_0657657
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buse()
        {
            this.TypeFilaments = new HashSet<TypeFilament>();
            this.ConfigPhysiques = new HashSet<ConfigPhysique>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public Nullable<int> FabricantId { get; set; }
        public float DiametreIn { get; set; }
        public float DiametreOut { get; set; }
    
        public virtual Fabricant Fabricant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeFilament> TypeFilaments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigPhysique> ConfigPhysiques { get; set; }
    }
}
