//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2_0657657
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigLogique
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfigLogique()
        {
            this.Essaies = new HashSet<Essaie>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ImprimanteId { get; set; }
        public Nullable<float> EpaisseurCouche { get; set; }
        public Nullable<float> Remplissage { get; set; }
        public string Description { get; set; }
        public bool DeBase { get; set; }
    
        public virtual Imprimante Imprimante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Essaie> Essaies { get; set; }
    }
}
