//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2_0657657
{
    using System;
    using System.Collections.Generic;
    
    public partial class EssaieFilament
    {
        public int EssaieId { get; set; }
        public int FilamentId { get; set; }
        public float QteUtilise { get; set; }
    
        public virtual Essaie Essaie { get; set; }
        public virtual Filament Filament { get; set; }
    }
}
