//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2_0657657
{
    using System;
    using System.Collections.Generic;
    
    public partial class Essaie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Essaie()
        {
            this.EssaieFilaments = new HashSet<EssaieFilament>();
        }
    
        public int ID { get; set; }
        public System.DateTime TempsDepart { get; set; }
        public Nullable<int> DureeReele { get; set; }
        public Nullable<int> DureeEstime { get; set; }
        public string Commentaire { get; set; }
        public Nullable<int> ConfigLogiqueId { get; set; }
        public Nullable<int> ImpressionId { get; set; }
        public Nullable<int> PourcentageReussi { get; set; }
        public Nullable<int> ConfigPhysiqueId { get; set; }
    
        public virtual ConfigLogique ConfigLogique { get; set; }
        public virtual ConfigPhysique ConfigPhysique { get; set; }
        public virtual Impression Impression { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EssaieFilament> EssaieFilaments { get; set; }
    }
}
