//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2_0657657
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilamentUtilise
    {
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Couleur { get; set; }
        public string Materiel { get; set; }
        public Nullable<double> QteTotal { get; set; }
    }
}
