//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2_0657657
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filament()
        {
            this.EssaieFilaments = new HashSet<EssaieFilament>();
        }
    
        public int ID { get; set; }
        public string Couleur { get; set; }
        public float LongueurInitiale { get; set; }
        public Nullable<System.DateTime> DateAchat { get; set; }
        public Nullable<int> ProprietaireId { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public Nullable<float> PoidInitial { get; set; }
        public Nullable<int> TypeFilamentId { get; set; }
        public Nullable<int> FabricantId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EssaieFilament> EssaieFilaments { get; set; }
        public virtual Fabricant Fabricant { get; set; }
        public virtual Usager Usager { get; set; }
        public virtual TypeFilament TypeFilament { get; set; }
    }
}
