//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2_0657657
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impression
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Impression()
        {
            this.Essaies = new HashSet<Essaie>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UsagerId { get; set; }
        public string Nom { get; set; }
        public Nullable<int> CreationId { get; set; }
        public System.DateTime DateImpression { get; set; }
        public string Commentaire { get; set; }
    
        public virtual Creation Creation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Essaie> Essaies { get; set; }
        public virtual Usager Usager { get; set; }
    }
}
