//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2_0657657
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imprimante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Imprimante()
        {
            this.ConfigLogiques = new HashSet<ConfigLogique>();
            this.ConfigPhysiques = new HashSet<ConfigPhysique>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public decimal Prix { get; set; }
        public Nullable<int> ModeleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigLogique> ConfigLogiques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigPhysique> ConfigPhysiques { get; set; }
        public virtual ModeleImprimante ModeleImprimante { get; set; }
    }
}
