//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2_0657657
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTable
    {
        public int ID { get; set; }
        public System.DateTime DateEvenement { get; set; }
        public string Evenement { get; set; }
        public int IdOriginal { get; set; }
        public string MaterielOriginal { get; set; }
        public Nullable<float> DiametreOriginal { get; set; }
        public string MaterielNouveau { get; set; }
        public Nullable<float> DiametreNouveau { get; set; }
    }
}
