//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2_0657657
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModeleImprimante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModeleImprimante()
        {
            this.Imprimantes = new HashSet<Imprimante>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public Nullable<int> FabricantId { get; set; }
    
        public virtual Fabricant Fabricant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imprimante> Imprimantes { get; set; }
    }
}
